apiVersion: v1
kind: Secret
metadata:
  name: postgresql-16-credentials
  namespace: postgres
type: kubernetes.io/basic-auth
stringData:
  username: app
  password: "dOeiCwNbaqeee0MbEdVCKCazLvIrgVRx"
