apiVersion: v1
kind: Secret
metadata:
  name: postgresql-18-credentials
  namespace: postgres
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: "ixFIQwxwMFUCEYzHEmmJ7dRpYh7cYb3s"
