apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-18
  namespace: postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0-system-trixie
  enableSuperuserAccess: true

  storage:
    size: 8Gi
    storageClass: local-path

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"

  bootstrap:
    initdb:
      database: defaultdb
      owner: postgres
      secret:
        name: postgresql-18-credentials

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

  monitoring:
    enablePodMonitor: false
