apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: write-pane-run-tls
  namespace: writefreely
spec:
  secretName: write-pane-run-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - write.pane.run
