apiVersion: v1
kind: ConfigMap
metadata:
  name: writefreely-config
  namespace: writefreely
data:
  config.ini: |
    [server]
    hidden_host          =
    port                 = 8080
    bind                 = 0.0.0.0
    tls_cert_path        =
    tls_key_path         =
    autocert             = false
    templates_parent_dir = .
    static_parent_dir    = .
    pages_parent_dir     = .
    keys_parent_dir      = .

    [database]
    type     = sqlite3
    filename = /data/writefreely.db
    username =
    password =
    database =
    host     =
    port     =

    [app]
    site_name         = Write
    site_description  = A place to write
    host              = https://write.pane.run
    theme             = write
    editor            = pad
    disable_js        = false
    webfonts          = true
    landing           = /
    simple_nav        = false
    wf_modesty        = false
    chorus            = false
    forest            = false
    disable_drafts    = false
    single_user       = false
    open_registration = false
    min_username_len  = 3
    max_blogs         = 5
    federation        = false
    public_stats      = true
    monetization      = false
    notes_only        = false
    private           = false
    local_timeline    = true
    user_invites      = user
    default_visibility = public
