apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-errors
  namespace: auth
  labels:
    app: oauth2-proxy
spec:
  type: ExternalName
  externalName: oauth2-proxy.auth.svc.cluster.local
  ports:
    - name: http
      port: 80
      targetPort: 4180
