apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-keys
  namespace: debian-ssh
data:
  authorized_keys: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBtCQO0LdDtTIwZIDYaQwZZo1ZGIxVUceiIgkjo0f8R7 seupedro
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICe1cpa+QE1oQTgvpqqPSXqpomnlQd+625m6tDHbu/i4 seupedro@mobile
