apiVersion: v1
kind: Namespace
metadata:
  name: debian-ssh
  labels:
    name: debian-ssh
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
