apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
  namespace: headlamp
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`headlamp.pane.run`)
    kind: Rule
    services:
    - name: oauth2-proxy-headlamp
      port: 80
  tls:
    secretName: headlamp-tls
