apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zitadel-tls
  namespace: zitadel
spec:
  secretName: zitadel-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - zitadel.pane.run
