apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{APP_NAME}}-tls
  namespace: {{APP_NAME}}
spec:
  secretName: {{APP_NAME}}-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - {{SUBDOMAIN}}.pane.run
