apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: searxng-pane-run-tls
  namespace: searxng
spec:
  secretName: searxng-pane-run-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - searxng.pane.run
