---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-16-app-user
  namespace: postgres-16
spec:
  encryptedData:
    password: AgBI8tnqbwGAW/JJW9yw39aggkbRRvBlngTbsyEzlqmCxi5DVDB5jwoQx0dMl2jba5UoIWcuz7EJEGuwGD4H+tJRHN8M0JGf/PsuvZTDLaNFjdwf9N+XS21WB+466BBkOnA35eod3601fHgcoEpWSt8gsXNSQouFF0k5y4svY26Y6S8SCpSoOkm1RxYqtAT4bTvWdSQQE2RdNBEZklHmJXROeCmf/sB4Eu2OoNNMch2BNFjY6/91pnMvNYuWSXz5Rr9lJJUKv/Hhk1MfOvrzE1sdeNzLGv/v7472ixjycahk4h1JMjizuN1Fm6C/ro6R0BcWg9/5XOXmSgik4imL9YKMvDUB6Tul6dw6MIVHIzfS9ZrqKSJNQ1HE+6bH5H223BYeycNkBDHHuht8acc8Sf5onJayHWgr6g+vymJDgBN3x3+Nk/cbh7mKcxLQVQTu48ts3ChieHl3Luo74VhXlhEPxlpE5vCIZy0tE2EMDS3dSninbNxZMaw4RZPgAnjDsQyux45RkD8vPX7VMPUEIZaDV38qB5tEul2s57VFy1f1A8b3i7OvR6tkvCMIajnis51PTedaqqvFrtMfOkgFv4ZUiofRy6/laKWB7ce9xzVxzEHPbIAqABl2mdYLue9+ml3G10cgSYa2byVtlBo90zdPNfY120L+zfrV0ZRUB0VH4v6oOj4XvbxMoPjnkKOxldIIuqoZGkwDVaIPle6xfQDgYzKaduVKdEkDWovmYVrIr4Ah6+Ne34X44a7VHcw=
    username: AgDNVJUaAgYx64+SKLAgW6dKx75roxGrSQLduYCvHAqI5zAVwjyd4mBgKM72AG7iVJ4ISlDwe2HeoC0q2lgjKgdTx/oFSkwobv91iZZAc81nQ/NX+asj1Cnhb2zKQaR1TKUwtwk8r/RqDNiNjPrf1Je+wQIOVVRgi0U1yTo0X1e++ScphDKLv/e/YJI7hFxgtUPo6WUX+3+usaENX8yMpURpouTI5e9Iwu2jJioVA1OwgDvi8iugn12YoPoGmGmJBXqgHzmimtUqQaoSNBawTI8/SAN8EBhILMJGc4HkHdVg9642AUKritLqXskBMakfnIg2EQMLTwgtdzcT9Mjey2KGzMrXyQONUelYsmTT7c9CYy6uefQuK26LTz3oxxGYoKPkQCck2nGRn6PlScsskMwn0CEGfKzaSfXWsvY5dXX5wBzQjxu7cyi1DYa1u2w34yHFjjqJsn260CaIderlhcSXDKi/p6HUkCLh0wxgNfIQV94jwfL86POeb/z5l7E7r7P6VhR7NSBSs6sEAlxxut09QiT9XGqGVcwcJ7l0Zlwr0LZjh+Z5Jf1Aaev/zjJey0J8crLU4iHAVhKnKjtng4rAxCAWwEGPT+wcX9dsZD05jrT3QLvPo73hYQWlIfcwq/cGulbvr5+XWzkYLYBjYesvUT36V+HEhhk3jxBRmPcdzNnV3ZKVvJLT0X4fZNlW3DX1bfc=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-16-app-user
      namespace: postgres-16
